### PR TITLE
Improve Memory Usage, add a build flag

### PR DESCRIPTION
**Pull request by javelinanddart**

### CODE REVIEW

**Comment by cuzz1369** [comment]
I'm running a test now with this

**Comment by javelinanddart** [comment]
Can we merge this?

**Comment by cuzz1369** [comment]
My build failed but unrelated to this and than you added more. Is this tested...for real?

**Comment by javelinanddart** [comment]
Unfortunetely, no. It's been used before, but I haven't had time to test it
between school and the build server I use being down (D's PC)

**Comment by javelinanddart** [comment]
At least, down when I had the time to build it

**Comment by cuzz1369** [comment]
K, I'll run a test now.

**Comment by javelinanddart** [comment]
Thank you.

**Comment by cuzz1369** [comment]
Failed http://pastebin.com/K9D2Tycu

**Comment by javelinanddart** [comment]
Fixed

**Comment by javelinanddart** [comment]
Will rebase if it works

**Pull request merged**
