### PR TITLE
candy5 : Fix OTA Libs For 64bit Devices

### PR DESCRIPTION
**Pull request by Meninblack007**
OTA Libs Will Be Handled From Build Repo.

Signed-off-by: Men_in_black007 <sanyam.53jain@gmail.com>

### CODE REVIEW

**Comment by Meninblack007** [comment]
@cuzz1369 @rc420head 
Check It Before Merging :P

**Comment by rc420head** [comment]
Ok I'll try after work with m9 build

**Comment by Meninblack007** [comment]
Okays!
I Tried It a on Yu Yureka aka Tomato(64bit device)
Worked fine....

**Comment by cuzz1369** [comment]
Testing now. Will merge in 30 mins if all goes well

**Comment by mkodekar** [comment]
Well com Sanyam

**Pull request merged**
